# number1 = int(input("Введите первое число: " ))
# number2 = int(input("Введите второе сило: "))
# print(number1+number2)

# numder1 = int(input("Введите первое число: "))
# number2 = int(input("Введите второе число: "))
# print(number1-number2)

# number1 = int(input("Введите первое число: "))
# number2 = int(input("Введите второе число: "))
# number3 = int(input("введите третье число: "))
# print((number1*number2)/number3)

# x = int(input("Введите первое число: "))
# y = int(input("Введите второе число: "))
# z = int(input("Введите третье число: "))
# print((x+y)*z)
# #------------
# number1 = 5
# number2 = 10
# print(number1+number2)

# numder1 = 10
# number2 = 5
# print(number1-number2)

# number1 = 20
# number2 = 5
# number3 = 2
# print((number1*number2)/number3)

# x = 10
# y = 5
# z = 2
# print((x+y)*z)

# print(10>5)
# print(10<5)

import calendar
yy = 2024
mm1 = 1
mm2 = 2
mm3 = 3
mm4 = 4
mm5 = 5
mm6 = 6
mm7 = 7
mm8 = 8
mm9 = 9
mm10 = 10
mm11 = 11
mm12 = 12
print(calendar.month(yy, mm1))
print(calendar.month(yy, mm2))
print(calendar.month(yy, mm3))
print(calendar.month(yy, mm4))
print(calendar.month(yy, mm5))
print(calendar.month(yy, mm6))
print(calendar.month(yy, mm7))
print(calendar.month(yy, mm8))
print(calendar.month(yy, mm9))
print(calendar.month(yy, mm10))
print(calendar.month(yy, mm11))
print(calendar.month(yy, mm12))