# number1 = int(input("Введите первое число: " ))
# number2 = int(input("Введите второе сило: "))
# print(number1+number2)

# numder1 = int(input("Введите первое число: "))
# number2 = int(input("Введите второе число: "))
# print(number1-number2)

# number1 = int(input("Введите первое число: "))
# number2 = int(input("Введите второе число: "))
# number3 = int(input("введите третье число: "))
# print((number1*number2)/number3)

# x = int(input("Введите первое число: "))
# y = int(input("Введите второе число: "))
# z = int(input("Введите третье число: "))
# print((x+y)*z)
# #------------
# number1 = 5
# number2 = 10
# print(number1+number2)

# numder1 = 10
# number2 = 5
# print(number1-number2)

# number1 = 20
# number2 = 5
# number3 = 2
# print((number1*number2)/number3)

# x = 10
# y = 5
# z = 2
# print((x+y)*z)

# print(10>5)
# print(10<5)

import calendar
yy = 2024
mm = 12
print(calendar.month(yy, mm))